Considering primary data that start before simulation.
ie3-institute/simona pull request #1038
Opened 2024-11-20 08:08 UTC by staudtMarius

Resolves #1034

2025-03-11 12:08 UTC, sebastian-peter reviewed
Thanks for putting in the effort. I've been looking through the code and kept thinking that we should just integrate this into `getTimeKeysAfter` and make it the PSDM's job.... That'd make it less complicated here.

2025-03-11 12:31 UTC, staudtMarius commented
I will create an PSDM issue for this.

2025-08-29 12:30 UTC, sebastian-peter requested changes
Some points from my side, looks mostly ready

2025-08-29 12:30 UTC, sebastian-peter commented on src/main/scala/edu/ie3/simona/service/primary/PrimaryServiceWorker.scala
> +            log.debug(
This should be a `log.warn` imho

2025-08-29 12:30 UTC, sebastian-peter commented on src/main/scala/edu/ie3/simona/service/primary/PrimaryServiceWorker.scala
> +            Success(initializedStateData, maybeNextTick)
We should start at tick 0 then, right? 

```suggestion
            Success(initializedStateData, Some(0L))
```

(This also makes more sense when looking at the case before this one, where we fail because we only have data _after_ simulation start.)

2025-08-29 12:30 UTC, sebastian-peter commented on src/main/scala/edu/ie3/simona/service/primary/PrimaryServiceWorker.scala
> +      case Some(nextTick) if nextTick > currentTick =>
This does not happen at all, I think. The previous code was fine the way it was. Or do you have any counter-example?

2025-09-01 11:01 UTC, staudtMarius commented on src/main/scala/edu/ie3/simona/service/primary/PrimaryServiceWorker.scala
> +      case Some(nextTick) if nextTick > currentTick =>
There is a test, where we request data for tick 200 an receive a completion for tick 900. Therefore, I added this code. Otherwise we would not be scheduled for tick 900.

If you have a better solution for the problem, please let me know.

2025-09-02 10:42 UTC, sebastian-peter commented on src/main/scala/edu/ie3/simona/service/primary/PrimaryServiceWorker.scala
> +      case Some(nextTick) if nextTick > currentTick =>
I think the test is erroneous. Here, we are told by the service that we want to get activated at 900:

https://github.com/ie3-institute/simona/blob/8883013c5fc2561e1cda34f72b29115fb9b532ae/src/test/scala/edu/ie3/simona/service/primary/PrimaryServiceWorkerSpec.scala#L400-L407

Right after that, we activate the service at 200:

https://github.com/ie3-institute/simona/blob/8883013c5fc2561e1cda34f72b29115fb9b532ae/src/test/scala/edu/ie3/simona/service/primary/PrimaryServiceWorkerSpec.scala#L412

This should not happen in reality.

2025-09-02 11:32 UTC, staudtMarius commented on src/main/scala/edu/ie3/simona/service/primary/PrimaryServiceWorker.scala
> +      case Some(nextTick) if nextTick > currentTick =>
I find it interesting that the actual tick value is not checked. Maybe we should add some code to check the value of the activation message. Or is this already handled elsewhere.

2025-09-02 12:55 UTC, sebastian-peter commented on src/main/scala/edu/ie3/simona/service/primary/PrimaryServiceWorker.scala
> +      case Some(nextTick) if nextTick > currentTick =>
This is naturally handled by the scheduler, who only activates actors according to the tick that they scheduled themselves for. I'm not against adding a check here, though, if you think that one is needed.

2025-09-03 09:52 UTC, staudtMarius commented on src/main/scala/edu/ie3/simona/service/primary/PrimaryServiceWorker.scala
> +      case Some(nextTick) if nextTick > currentTick =>
After checking the code again, I think we don't need a check here.

2025-09-03 11:02 UTC, sebastian-peter approved these changes
LGTM, thanks for being patient with my requests!

2025-09-03 11:02 UTC, merged