Mh/#1065 java to scala durations
ie3-institute/simona pull request #1068
Opened 2024-12-13 13:04 UTC by marvinheintze

Resolves #1065 

Changed the java.time.Duration to scala.concurrent.duration.Duration
and changed the Duration to a FiniteDuration in some classes

2025-02-13 18:02 UTC, sebastian-peter requested changes
There's more Java Durations, does it make sense to convert them too?
To be exact, `resolution` and `sweepTimeout` in `Powerflow`

2025-02-19 07:38 UTC, staudtMarius commented
> There's more Java Durations, does it make sense to convert them too? To be exact, `resolution` and `sweepTimeout` in `Powerflow`

I have adapted these parts. Also, I removed the no longer necessary conversion in `SimonaConfig`.

2025-02-19 09:26 UTC, sebastian-peter requested changes

2025-02-19 09:26 UTC, sebastian-peter commented on src/main/scala/edu/ie3/simona/agent/grid/GridAgent.scala
> +
Still there...

2025-02-19 09:26 UTC, sebastian-peter commented on src/main/scala/edu/ie3/simona/config/ConfigFailFast.scala
> +    val hasMillis = (powerFlow.resolution.toMillis / 1e3) % 1 != 0
What's better about this than using `!= 0`?

2025-02-19 09:26 UTC, sebastian-peter commented on src/test/scala/edu/ie3/simona/agent/grid/PowerFlowSupportSpec.scala
> +      FiniteDuration.apply(30, MINUTES),
Ok well, doing this myself now :D

2025-02-19 09:31 UTC, sebastian-peter commented on src/main/scala/edu/ie3/simona/config/ConfigFailFast.scala
> +    val hasMillis = (powerFlow.resolution.toMillis / 1e3) % 1 != 0
Ah, I think I get it

2025-02-19 09:34 UTC, sebastian-peter commented on src/main/scala/edu/ie3/simona/agent/grid/GridAgent.scala
> +
Removed it

2025-02-19 09:35 UTC, sebastian-peter approved these changes

2025-02-19 10:07 UTC, merged