Run log filter threshold from xml
ie3-institute/simona pull request #109
Opened 2022-01-25 07:48 UTC by ckittl

Resolves #108

2022-01-25 07:51 UTC, ckittl commented
Restart of rolling file appender does not work too great, yet. If required, I would have to look into this in detail.

@johanneshiry I assume this is the intended behavior? Or did you intend the log file in output directory only have "INFO"-Level and above? In that case I'd need to adapt the implementation.

2022-01-25 13:37 UTC, sebastian-peter submitted a review, later dismissed
LGTM

2022-02-16 20:24 UTC, johanneshiry commented
> Restart of rolling file appender does not work too great, yet. If required, I would have to look into this in detail.
> 
> 
> 
> @johanneshiry I assume this is the intended behavior? Or did you intend the log file in output directory only have "INFO"-Level and above? In that case I'd need to adapt the implementation.

The main intention is to **always** have a log file with the INFO-level in the output directory. If you want to have additional logs with more detailed log levels you can just adapt additional appenders in the xml-config. Therefore I would prefer not changing this behavior, but leave it to the user in the xml config to configure additional logger with e.g. debug level or below. 
Background: I always want at least **one** non-cluttered info log in the output dir. If you want debug log it can be **additionally** configured in the xml config file.

2022-02-16 20:25 UTC, johanneshiry requested changes
See comment regarding your question. If required we can discuss this further. Pls let me know if you want to do so.

2022-05-02 13:36 UTC, t-ober commented
`
        rootLogger.iteratorForAppenders().asScala.foreach {
          case rf: RollingFileAppender[_] =>
            rf.getTriggeringPolicy.start()
            rf.start()
          case appender => appender.start()
        }
`
in LofbackConfiguration#default fixes the main issue.

2023-07-31 12:15 UTC, danielfeismann commented on CHANGELOG.md
> +- Location of `vn_simona` test grid (was partially in Berlin and Dortmund)
Does this apply to this PR?

2023-07-31 12:15 UTC, danielfeismann requested changes
Looks good to me, just one very minor question.

2023-08-01 09:23 UTC, danielfeismann commented on CHANGELOG.md
> +- Take log file event filters from `logback.xml` when defining the run log appender
Issue No.

2023-08-01 12:38 UTC, danielfeismann approved these changes
LGTM

2023-08-01 12:39 UTC, merged