Properly updating scapegoat to 1.4.12
ie3-institute/simona pull request #115
Opened 2022-01-25 14:49 UTC by sebastian-peter

2022-01-25 16:23 UTC, johanneshiry commented on build.gradle
>    implementation 'org.locationtech.jts.io:jts-io-common:1.18.2'
@sebastian-peter would you mind excluding junit pls (cf. build.gradle @ PowerSystemUtils)

2022-01-25 16:38 UTC, johanneshiry requested changes
Thx for your work. Added two suggestions and one question. :)

2022-01-25 16:38 UTC, johanneshiry commented on src/main/scala/edu/ie3/simona/agent/grid/DBFSAlgorithm.scala
> +          )
Match is not exhaustive. 

Therefore I would propose sth like e.g.:

```
    gridAgentBaseData.sweepValueStores.lastOption.map {
      case (_, valueStore) =>
        notifyListener(
          this.createResultModels(
            gridAgentBaseData.gridEnv.gridModel,
            valueStore
          )(
            currentTimestamp
          )
```

2022-01-25 16:38 UTC, johanneshiry commented on src/main/scala/edu/ie3/simona/model/participant/load/profile/LoadProfileStore.scala
> +              )
If this cannot happen, avoid the exception. This means, please refactor this part such that a mapping is only produced if maxConsuption is available. Something like the following pseudo code should do the trick: 

```
knownLoadProfiles
      .flatMap(loadProfile => {
       loadProfile match {
         case BdewLoadProfile.H0 => 
            ....maxOption
        }.map(maxConsumption => loadProfile -> maxConsumption)
      }).toMap
```

2022-01-25 16:38 UTC, johanneshiry commented on src/main/scala/edu/ie3/simona/service/weather/WeatherSource.scala
> +        /* There is more than one coordinate existent */
Invalid comment. There may be more than ONE or NONE coordinates existent

2022-01-25 16:38 UTC, johanneshiry commented on src/main/scala/edu/ie3/simona/sim/setup/SetupHelper.scala
> +      .flatMap(_._2.headOption)
:+1:

2022-01-25 16:38 UTC, johanneshiry commented on src/test/scala/edu/ie3/simona/event/listener/ResultEventListenerSpec.scala
> -        resultFileLines.tail.size shouldBe 1
Why the removed equals to one element?

2022-01-25 21:23 UTC, johanneshiry approved these changes
Perfect! Thank you! 🥇

2022-01-26 08:50 UTC, ckittl approved these changes

2022-01-26 08:52 UTC, merged