create an about page for the documentation
ie3-institute/simona pull request #199
Opened 2022-04-19 12:51 UTC by lararou

resolve #187

2022-05-03 13:45 UTC, danielfeismann requested changes
Thanks for your work, this looks great. I just have minor comments which could be changed in my point of view.

2022-05-03 13:45 UTC, danielfeismann commented on docs/readthedocs/about.md
> +Simona is a simulation-tool for generating time-series in the context of distribution grids to be used in grid planning, operation and analysis. The simulation is executed using an agent-based, discr
I would go for SIMONA in capital letters and I think it is simulation tool as well as time-series as separate words.

2022-05-03 13:45 UTC, danielfeismann commented on docs/readthedocs/about.md
> +With Simona, you can model your power grid using a broad variety of different available asset types. The input data for the grid must be provided as PSDM-data. (For more information on this data type
I would suggest to have the Hyperlinks also with a floating window (check the link to PSDM at Line Model for example https://simona--199.org.readthedocs.build/en/199/models/line_model.html)

2022-05-03 13:45 UTC, danielfeismann commented on docs/readthedocs/about.md
> +![Simona_messages](images/usersguide/agent_messages.png "Simona Agent Messages")
I would suggest to have this picture with maybe 60% width to have it smaller...

2023-02-20 12:40 UTC, staudtMarius approved these changes

2023-02-20 13:10 UTC, sebastian-peter requested changes
Thanks for taking over this PR! I found a bunch of things that need more fixing.

2023-02-20 13:10 UTC, sebastian-peter commented on docs/readthedocs/about.md
> +addition to that, a grid agent (GA) manages the interaction with other grid agents and with the subordinate SPAs.
"manages _interactions between subgrids_ and with"

2023-02-20 13:10 UTC, sebastian-peter commented on docs/readthedocs/about.md
> +Please, visit the SIMONA [website](https://simona.ie3.e-technik.tu-dortmund.de) for further Information. You will find
"_There you will also find_"

2023-02-20 13:10 UTC, sebastian-peter commented on docs/readthedocs/about.md
> +<img src="images/usersguide/agent_messages.png" alt="Simona Agent Message" width="60%" height="60%">
Image is broken on the [final page](https://simona--199.org.readthedocs.build/en/199/about.html)

2023-02-20 14:36 UTC, sebastian-peter requested changes
Sorry, the alt texts could also be better. That's all though, I think

2023-02-20 14:36 UTC, sebastian-peter commented on docs/readthedocs/about.md
> +![Basic Simona](images/usersguide/basic_simona_environment.png "SIMONA System Overview")
I think the alt text is the one in the beginning. So I would place the `SIMONA System Overview` text where currently `Basic Simona` is placed.

2023-02-20 14:36 UTC, sebastian-peter commented on docs/readthedocs/about.md
> +![SIMONA Agent Message](images/usersguide/agent_messages.png)
Alt text could rather be: "SIMONA message protocol overview"

2023-02-21 14:16 UTC, sebastian-peter approved these changes
Great, thanks!

@danielfeismann You might also have a final look.

2023-02-21 14:52 UTC, danielfeismann approved these changes
Looks good to me, thanks for the improvement of our documentation :)

2023-02-21 14:53 UTC, danielfeismann commented
!test

2023-02-21 15:53 UTC, merged