Updating reviewers in dependabot config
ie3-institute/simona pull request #247
Opened 2022-05-30 09:37 UTC by sebastian-peter

Resolves #246

2022-05-30 09:42 UTC, danielfeismann requested changes

2022-05-30 09:42 UTC, danielfeismann commented on .github/dependabot.yml
>    - sebastian-peter
```suggestion
  - daniellfeismann
```

2022-05-30 12:50 UTC, danielfeismann approved these changes

2022-06-06 15:46 UTC, ckittl approved these changes
Like that! :-)

2022-06-06 17:36 UTC, merged