Create heatpump agent
ie3-institute/simona pull request #254
Opened 2022-06-06 16:13 UTC by ckittl

Resolves #253

2023-10-09 15:24 UTC, danielfeismann commented on src/main/scala/edu/ie3/util/scala/quantities/QuantityUtil.scala
> +        )
Unsure about this. Let's double check this.

2023-10-09 15:25 UTC, danielfeismann commented on src/main/scala/edu/ie3/util/scala/quantities/QuantityUtil.scala
> +            integrationUnit(lastValue.value.doubleValue * duration)
Unsure about this. Let's double check this.

2023-10-23 09:54 UTC, danielfeismann requested changes
Beside one minor thing this looks good to me. A second reviewer would be great since I also worked on this changes here...

2023-10-23 09:54 UTC, danielfeismann commented on src/main/scala/edu/ie3/simona/agent/participant/hp/HpAgentFundamentals.scala
> +      new ThermalHouseInput(
Do we want to create some random thermal bus if the correct one can't be found? From my point of view an exception would be better here. Or?

2023-10-25 15:01 UTC, danielfeismann commented on src/main/scala/edu/ie3/simona/agent/participant/hp/HpAgentFundamentals.scala
> +      new ThermalHouseInput(
After discussing this shortly we opt for an exception in this case.

2023-11-22 09:25 UTC, sebastian-peter requested changes
There's some more things one could discuss, but these are all topics for another day.

2023-11-22 09:25 UTC, sebastian-peter commented on src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgentFundamentals.scala
> +  def averageApparentPowerAndHeat(
Here, we could re-use `averageApparentPower` instead of duplicating all this code.

2023-11-22 09:25 UTC, sebastian-peter commented on src/main/scala/edu/ie3/simona/io/grid/CsvGridSource.scala
> +  def readGrid(
This method is not used, we implemented it in PSDM

2023-11-22 17:40 UTC, sebastian-peter approved these changes
Thanks for taking care of my comments!

2023-11-22 17:58 UTC, merged