RuntimeEvent kafka sink
ie3-institute/simona pull request #262
Opened 2022-06-13 11:10 UTC by sebastian-peter

Resolves #242

2022-06-20 14:03 UTC, t-ober requested changes
Looks very nice - thanks ! Just minor stuff.

2022-06-20 20:09 UTC, sebastian-peter commented on src/main/scala/edu/ie3/simona/config/ConfigFailFast.scala
> +    )
`eventsToProcess` can be `None`, in which case no filter is applied to received runtime events

2022-06-20 20:09 UTC, sebastian-peter commented on src/main/scala/edu/ie3/simona/event/listener/RuntimeEventListener.scala
> +        case None => processEvent(listeners, event, ctx.log)
That's how it works?

2022-06-20 20:13 UTC, sebastian-peter commented on src/main/scala/edu/ie3/simona/event/listener/RuntimeEventListener.scala
> +      queue.map(qu => RuntimeEventQueueSink(qu))
It's currently only used in tests. I added some ScalaDoc to all sinks now

2022-06-20 20:24 UTC, sebastian-peter commented on src/main/scala/edu/ie3/simona/io/runtime/RuntimeEventLogSink.scala
> +    }
Check out `RuntimeEventListener#apply`. A log sink is always initialized and the queue sink is only initialized if a queue was supplied. Same thing with the kafka sink: Only if corresponding configuration is present, such a sink is initialized and used.
I added some documentation which could be useful here.

2022-06-21 07:43 UTC, sebastian-peter commented
I think we should wait until we completed some integration tests with simona-service here. I don't currently don't foresee any problems here, but let's wait until that's tested.

2022-06-30 20:48 UTC, sebastian-peter commented
The manual integration tests completed with success.

2022-08-02 07:16 UTC, t-ober submitted a review, later dismissed

2022-08-02 17:30 UTC, t-ober approved these changes

2022-08-02 17:30 UTC, merged