Implementation of typed two-parted scheduler
ie3-institute/simona pull request #592
Opened 2023-08-23 21:45 UTC by sebastian-peter

Resolves #378

Some notes:
The new scheduler only stores one activation for an actor at a time.
This also means that trigger revocation happens automatically.

Adjacent changes are the following:
- CompletionMessage can only contain one trigger and should only schedule the completing actor. For other schedulings, the ScheduleTriggerMessage is used (for now)
- Removed actor reference from TriggerWithIdMessage, which has never been used

This is another step to move the scheduling mechanism in SIMONA more towards DEVS. There's more to come.

2023-11-17 14:00 UTC, danielfeismann requested changes
Thanks for your work especially for keeping ScalaDoc updated here as well. I mainly would like to double check if the todos are for the upcoming work - I least I guess so - and have some little questions.

2023-11-19 12:45 UTC, sebastian-peter commented on src/main/scala/edu/ie3/simona/scheduler/SchedulerData.scala
> +    ], // FIXME typed: Scheduler or time advancer
Fixed with #652

2023-11-19 12:47 UTC, sebastian-peter commented on src/main/scala/edu/ie3/simona/scheduler/TimeAdvancer.scala
> +    * schedulee to complete
This was actually on purpose, meaning the actor who got scheduled (schedulee) in contrast to the scheduling actor (scheduler). However, I'm very happy to replace this term if there's a better one...

2023-11-19 12:48 UTC, sebastian-peter commented on src/main/scala/edu/ie3/simona/api/ExtMessageUtils.scala
> +        // FIXME also update the documentation in usersguide.md accordingly
Both can be solved e.g. in #652 once https://github.com/ie3-institute/simonaAPI/pull/132 is merged and released

2023-11-19 12:51 UTC, sebastian-peter commented on src/main/scala/edu/ie3/simona/event/RuntimeEvent.scala
> +      noOfFailedPF: Int, // FIXME remove
Maybe we can have a short discussion on this with next sprint meeting. In my view, the choices are 1. move the power flow statistics to `RuntimeEventListener` or 2. remove it completely

2023-11-19 12:53 UTC, sebastian-peter commented on src/main/scala/edu/ie3/simona/ontology/messages/SchedulerMessage.scala
> +    * TODO rename to StartSimMessage
Yes, most of them are solved with #652 (as is this one - I wanted to keep this as short as possible, and renaming stuff can blow PRs up)

2023-11-19 12:53 UTC, sebastian-peter commented on src/main/scala/edu/ie3/simona/ontology/messages/SchedulerMessage.scala
> +    * TODO only for TimeAdvancer
Solved with #652

2023-11-22 14:48 UTC, danielfeismann approved these changes
LGTM, thanks :)

2023-11-22 14:48 UTC, merged