Print log directory to terminal upon simulation failure
ie3-institute/simona pull request #772
Opened 2024-03-13 11:39 UTC by staudtMarius

Resolves #626

2024-04-09 14:23 UTC, t-ober requested changes

2024-04-09 14:23 UTC, t-ober commented on src/main/scala/edu/ie3/simona/main/RunSimona.scala
> +    }
This should take into account the actual output directory that was specified in the configuration. It seems like the path you are printing is relative to simona not based on the configuration

2024-06-18 11:17 UTC, sebastian-peter requested changes
Small suggestion from my side

2024-06-18 11:17 UTC, sebastian-peter commented on src/main/scala/edu/ie3/simona/sim/setup/SimonaStandaloneSetup.scala
> +    override val logOutputDir: String,
You could also add `override val logOutputDir: String = resultFileHierarchy.logOutputDir` to the class body instead. That way, we'll have one less variable within the class parameters.

2024-06-24 14:19 UTC, t-ober approved these changes

2024-06-26 15:05 UTC, sebastian-peter approved these changes

2024-06-26 17:21 UTC, merged