Fix not stopping correctly on failed power flow if configured to stop
ie3-institute/simona pull request #813
Opened 2024-05-24 06:02 UTC by staudtMarius

Resolves #800

2024-06-24 14:24 UTC, t-ober approved these changes

2024-06-26 14:18 UTC, sebastian-peter requested changes
Could you enhance `DBFSAlgorithmFailedPowerFlowSpec` with a test case where the inferior grid sends `FailedPowerFlow` to the center agent, which is then supposed to send the same to the superior agent.

2024-06-26 14:18 UTC, sebastian-peter commented on src/main/scala/edu/ie3/simona/agent/grid/DBFSAlgorithm.scala
> +
I am not really sure if this is what we want. If I recall correctly, `FailedPowerFlow` is supposed to "bubble up" towards the slack GridAgent, who then decides to quit DBFS simulation. But it looks like the information is not forwarded in `goToPowerFlowCalculationOrStay`.

So if everything actually worked, I think only the slack GridAgent should print out a warning that some subgrid has failed powerflow calculation. Additionally each GA in which Newton-Raphson actually failed, could print out a warning as well.

2024-07-01 07:16 UTC, staudtMarius commented on src/main/scala/edu/ie3/simona/agent/grid/DBFSAlgorithm.scala
> +              simulateGrid(gridAgentBaseData, currentTick)
I don't know. I adapted this part to be the same as the other case above.

2024-07-11 10:44 UTC, staudtMarius commented
!test

2024-07-15 15:02 UTC, sebastian-peter commented on src/main/scala/edu/ie3/simona/agent/grid/DBFSAlgorithm.scala
> +              simulateGrid(gridAgentBaseData, currentTick)
Looked into it once more, in this case we can just stop, actually.

2024-07-15 16:56 UTC, merged