Fix simulation stopping at unhandled messages in `DBFSAlgorithm`.
ie3-institute/simona pull request #823
Opened 2024-05-31 09:28 UTC by staudtMarius

Resolves #821

2024-06-11 15:00 UTC, sebastian-peter requested changes
Also question from my side: Was this an issue that also existed before the transition to pekko typed?

2024-06-11 15:00 UTC, sebastian-peter commented on src/main/scala/edu/ie3/simona/agent/grid/DBFSAlgorithm.scala
> +          ctx.log.debug(s"Received the message $message to early. Stash away!")
same as above

2024-06-11 15:18 UTC, staudtMarius commented
@sebastian-peter I never noticed this issue before the conversion to typed.

2024-06-11 17:06 UTC, sebastian-peter commented
@staudtMarius Then let's analyze what the problem is and where it comes from first before merging this

2024-06-26 14:21 UTC, sebastian-peter commented
@staudtMarius We still have a todo here if I remember correctly, which was specifying the messages that are supposed to be stashed

2024-07-08 13:14 UTC, sebastian-peter approved these changes
Thanks, looks good

2024-07-08 13:14 UTC, merged