Rewrote SystemComponentSpec from groovy to scala
ie3-institute/simona pull request #840
Opened 2024-07-01 09:45 UTC by pierrepetersmeier

SystemComponentTest convert from groovy to scala.

This PR is related to Issue https://github.com/ie3-institute/simona/issues/646

2024-07-04 09:02 UTC, danielfeismann commented on src/test/scala/edu/ie3/simona/model/SystemComponentSpec.scala
> +      TimeUtil.withDefaults.toZonedDateTime("2019-01-02T00:00:00Z")
same as above

2024-07-04 09:06 UTC, danielfeismann commented on src/test/scala/edu/ie3/simona/model/SystemComponentSpec.scala
> +      TimeUtil.withDefaults.toZonedDateTime("2019-01-02T00:00:00Z")
you can use simulationEnd (or defaultSimulationEnd) here

2024-07-04 09:07 UTC, danielfeismann commented on src/test/scala/edu/ie3/simona/model/SystemComponentSpec.scala
> +      TimeUtil.withDefaults.toZonedDateTime("2019-01-01T00:00:00Z")
and simulationStart here

2024-07-25 11:20 UTC, pierrepetersmeier commented
Is the simulation start and end time correctly implemented? I'm not sure. The test is now integrated into grid/systemcomponentspec.scala.

2024-07-25 13:19 UTC, danielfeismann requested changes

2024-07-25 13:19 UTC, danielfeismann commented on src/test/scala/edu/ie3/simona/model/SystemComponentSpec.scala
> +}
I guess this can be removed since is is already included in `scala/edu/ie3/simona/model/grid/SystemComponent.spec`

2024-07-25 13:19 UTC, danielfeismann commented on src/test/scala/edu/ie3/simona/model/grid/SystemComponentSpec.scala
> +        TimeUtil.withDefaults.toZonedDateTime("2019-01-02T00:00:00Z")
Sorry, I just realized we need to have different times for the test than the default ones. My bad. 

Two options
1. add `with DefaultTestData` to the class defintion above, remove defaultSimulationStart from line 75 / 76 and rename `defaultSimulationEnd` to `simulationEnd`.
2. Only do renaming, so remove the `default` from both variables here.

2024-07-25 13:19 UTC, danielfeismann commented on src/test/scala/edu/ie3/simona/model/grid/SystemComponentSpec.scala
> +        TimeUtil.withDefaults.toZonedDateTime("2019-01-02T00:00:00Z")
same as above, should be done the same way.

2024-07-30 07:30 UTC, danielfeismann approved these changes
LGTM!

2024-07-30 07:30 UTC, merged