Add unapply method for ThermalHouseResults
ie3-institute/simona pull request #935
Opened 2024-08-24 09:11 UTC by danielfeismann

resolves #934

2024-11-14 10:49 UTC, staudtMarius requested changes
Looks good to me. I found two parts that could be improved.

2024-11-14 10:49 UTC, staudtMarius commented on src/main/scala/edu/ie3/simona/event/ResultEvent.scala
> +    ] = {
The brace can be removed.

2024-11-14 10:49 UTC, staudtMarius commented on src/main/scala/edu/ie3/simona/event/ResultEvent.scala
> +    ] = {
See above.

2024-11-14 17:15 UTC, sebastian-peter requested changes
I like this idea. Just some minor code formatting points.

2024-11-15 11:50 UTC, sebastian-peter approved these changes

2024-11-15 12:03 UTC, merged