Simplified methods to values in ThermalHouse
ie3-institute/simona pull request #952
Opened 2024-09-09 14:27 UTC by marvinheintze

Resolves #940 

Changed the methods `calcInnerTemperatureChange`, `calcThermalEnergyChange `and `calcThermalEnergyGain` to values `thermalEnergyLoss`, `thermalEnergyGain`, `temperatureChange`.

`calcInnerTemperatureChange `and `calcNewInnerTemperature `were put together in `val temperatureChange`

`thermalConductanceToEnergy` was changed to `calcThermalEnergyChange`

`def calcThermalEnergyLoss` was removed and is instead calculated in value `thermalEnergyLoss`

2024-09-16 14:15 UTC, sebastian-peter requested changes
Please don't forget adding to changelog as well :)

2024-09-16 14:15 UTC, sebastian-peter commented on src/test/scala/edu/ie3/simona/model/thermal/ThermalHouseSpec.scala
> +      val newInnerTemperature = innerTemperature + innerTemperatureChange
This test can just be removed alltogether. The methods that were formerly tested don't exist anymore.

2024-09-16 14:15 UTC, sebastian-peter commented on src/main/scala/edu/ie3/simona/model/thermal/ThermalHouse.scala
Looks good so far. Now we've gone a little bit _too_ far in the other direction and a bit more explanation would be nice 😄 The goal would be to understand what is happening at first glance.

My suggestions (open for other/additional suggestions though):
- For `val thermalEnergyLoss`: Add comment above `// thermal energy loss due to the deviation between outside and inside temperature`
- Introduce `val energyChange = thermalEnergyGain - thermalEnergyLoss`

2024-09-16 14:52 UTC, danielfeismann commented on src/main/scala/edu/ie3/simona/model/thermal/ThermalHouse.scala
To be fair: Marvin and myself discussed some of these points and I might pushed it a bit to far in the other direction :) We should add a comment and take Sebastians suggestions

2024-09-16 17:24 UTC, marvinheintze commented on src/main/scala/edu/ie3/simona/model/thermal/ThermalHouse.scala
I've added 2 additionial comments, I thought couldn't hurt. You can let me know if they should stay there or if i should remove them.

2024-09-17 08:01 UTC, sebastian-peter approved these changes
LGTM

2024-09-17 08:01 UTC, merged

2024-09-17 08:01 UTC, sebastian-peter commented on src/main/scala/edu/ie3/simona/model/thermal/ThermalHouse.scala
Looks good, thanks!