improve code quality in fixedloadmodelspec and other tests
ie3-institute/simona pull request #958
Opened 2024-09-16 11:25 UTC by pierrepetersmeier

improve code quality in fixedloadmodelspec and other tests 

resolves #919

2024-09-16 11:37 UTC, pierrepetersmeier commented
@sebastian-peter I hope everything fits now. Should all 'foreach' be converted to 'forall'?

2024-09-16 14:30 UTC, sebastian-peter requested changes

2024-09-16 14:30 UTC, sebastian-peter commented on src/test/scala/edu/ie3/simona/model/grid/SystemComponentSpec.scala
> +      testCases.foreach { case (operationStart, operationEnd, expected) =>
Please use `forAll(testCases)` as well :)

2024-09-16 14:30 UTC, sebastian-peter commented on src/test/scala/edu/ie3/simona/model/participant/WecModelSpec.scala
Could you try to introduce `forAll(testCases)` here as well? So for "calculate active power output depending on velocity", there would be twelve test cases and for "calculate active power output depending on temperature", there would be three. Don't know if it's understandable what I mean, please just let me know if not.

2024-09-16 14:30 UTC, sebastian-peter commented on src/test/scala/edu/ie3/simona/model/thermal/ThermalHouseSpec.scala
Yes, that's what I meant. Thanks!

2024-09-16 14:30 UTC, sebastian-peter commented on src/test/scala/edu/ie3/simona/model/participant/load/FixedLoadModelSpec.scala
> +        val scales = (0 to 20).map(_ * 0.1)
Could also probably be (0.0 to 2.0 by 0.1)

2024-09-18 14:34 UTC, sebastian-peter requested changes
Thanks for considering my requests. I only have one more pedantic wish.

2024-09-18 14:34 UTC, sebastian-peter commented on src/test/scala/edu/ie3/simona/model/grid/SystemComponentSpec.scala
> +      testCases.forall { case (operationStart, operationEnd, expected) =>
Please also use test cases with `forAll(testCases)` here. For this to work, the test cases have to be defined as a `Table`.

2024-09-18 14:34 UTC, sebastian-peter commented on src/test/scala/edu/ie3/simona/model/grid/SystemComponentSpec.scala
> +      } shouldBe true
... then here you'd still use `should be`

2024-09-19 08:36 UTC, merged